10 database relations
CA-G12/MoH pull request #11
Opened 2022-10-13 13:36 UTC by Nader-SH

2022-10-13 20:47 UTC, Raghad-Mezied requested changes

2022-10-13 20:47 UTC, Raghad-Mezied commented on server/models/adminProduct.ts
>  adminProduct.init(
Rename all your model to start with a capital.

2022-10-14 08:19 UTC, Ibtisam-Hemmo submitted a review, later dismissed

2022-10-14 20:23 UTC, Raghad-Mezied submitted a review, later dismissed

2022-10-14 21:28 UTC, AhmedAbuSharar approved these changes, later dismissed

2022-10-15 15:16 UTC, Ibtisam-Hemmo approved these changes, later dismissed

2022-10-16 07:14 UTC, Raghad-Mezied approved these changes

2022-10-16 07:14 UTC, merged