signup page - pharamcy/signup
CA-G12/MoH pull request #21
Opened 2022-10-16 08:33 UTC by Ibtisam-Hemmo

2022-10-16 18:35 UTC, Nader-SH approved these changes, later dismissed

2022-10-20 18:50 UTC, Raghad-Mezied requested changes

2022-10-20 18:50 UTC, Raghad-Mezied commented on client/src/components/Button.tsx
> +};
Move all types

2022-10-20 18:50 UTC, Raghad-Mezied commented on client/src/components/auth/Signup.tsx
> +  };
wrap all your code in try and catch, throw the error and handle it once in the catch.

2022-10-21 18:25 UTC, Raghad-Mezied approved these changes

2022-10-22 06:17 UTC, Nader-SH approved these changes

2022-10-22 17:24 UTC, AhmedAbuSharar approved these changes

2022-10-22 17:31 UTC, merged