[POST] /auth/signup
CA-G12/MoH pull request #22
Opened 2022-10-16 08:37 UTC by Ibtisam-Hemmo

2022-10-16 18:36 UTC, Nader-SH approved these changes, later dismissed

2022-10-16 21:50 UTC, Raghad-Mezied requested changes

2022-10-16 21:50 UTC, Raghad-Mezied commented on server/validation/signupSchema.ts
> +}
Move to interfaces

2022-10-16 21:50 UTC, Raghad-Mezied commented on server/controllers/authentication/signUp.ts
> +      role: 'pharmacy',
We need the image and the pharmacy_id not the owner_id

2022-10-16 21:50 UTC, Raghad-Mezied commented on server/controllers/authentication/signUp.ts
> +    return res.cookie('token', token).json(pharamcyData);
Send it with the status code 201, and send the json with the pattern `json({
  data,
  msg
})`

2022-10-16 21:50 UTC, Raghad-Mezied commented on server/controllers/authentication/signUp.ts
> +  }
This error could be the validation error, so we need to send it with the customError you did

2022-10-17 09:38 UTC, Raghad-Mezied requested changes

2022-10-17 09:38 UTC, Raghad-Mezied commented on server/controllers/authentication/signUp.ts
> +        next(new CustomError (401, 'you have a validation error when signing up'))
It's a validation error, the user enters something wrong so send an appropriate message and status code.

2022-10-17 10:02 UTC, Raghad-Mezied approved these changes, later dismissed

2022-10-17 11:24 UTC, Nader-SH approved these changes, later dismissed

2022-10-18 16:49 UTC, Raghad-Mezied submitted a review, later dismissed

2022-10-18 17:26 UTC, Raghad-Mezied approved these changes

2022-10-18 17:28 UTC, Nader-SH approved these changes

2022-10-18 17:29 UTC, AhmedAbuSharar approved these changes

2022-10-18 17:29 UTC, merged