Error middleware
CA-G12/MoH pull request #24
Opened 2022-10-16 09:58 UTC by Ibtisam-Hemmo

2022-10-16 21:26 UTC, Raghad-Mezied requested changes

2022-10-16 21:26 UTC, Raghad-Mezied commented on server/validation/signupSchema.ts
> +}
Move to interfaces

2022-10-16 21:26 UTC, Raghad-Mezied commented on server/utils/generateToken.ts
> +
Move to interfaces

2022-10-16 21:26 UTC, Raghad-Mezied commented on server/utils/generateToken.ts
> +require('env2')('.env');
No need to require here as you did in your server file

2022-10-16 21:26 UTC, Raghad-Mezied commented on server/middlewares/Error.ts
> +});
The status and the message are from your error, not the custom error

2022-10-16 21:26 UTC, Raghad-Mezied commented on server/controllers/authentication/signUp.ts
> +    const licenseExisted = await Pharmacy.findOne({
Delete the signup part.

2022-10-17 09:15 UTC, Raghad-Mezied approved these changes

2022-10-17 11:22 UTC, AhmedAbuSharar approved these changes

2022-10-17 11:23 UTC, Nader-SH approved these changes

2022-10-17 13:42 UTC, merged