28 logout router new
CA-G12/MoH pull request #31
Opened 2022-10-16 17:49 UTC by Nader-SH

2022-10-16 21:20 UTC, Raghad-Mezied requested changes

2022-10-16 21:20 UTC, Raghad-Mezied commented on server/controllers/index.ts
>    // eslint-disable-next-line import/prefer-default-export
Remove this comment

2022-10-16 21:20 UTC, Raghad-Mezied commented on server/controllers/authentication/index.ts
>    // eslint-disable-next-line import/prefer-default-export
Remove the comment

2022-10-17 06:55 UTC, Ibtisam-Hemmo approved these changes

2022-10-17 08:25 UTC, Raghad-Mezied approved these changes

2022-10-17 08:42 UTC, AhmedAbuSharar approved these changes

2022-10-17 08:43 UTC, merged