12 pharmacy auth middleware
CA-G12/MoH pull request #33
Opened 2022-10-16 18:35 UTC by Ibtisam-Hemmo

2022-10-16 21:17 UTC, Raghad-Mezied requested changes

2022-10-16 21:17 UTC, Raghad-Mezied commented on server/middlewares/pharmacyAuth.ts
> +    next(401, 'You are not authenticated');
Use the CustomError, so we can do general handle for all errors

2022-10-16 21:17 UTC, Raghad-Mezied commented on server/middlewares/auth.ts
> +    next(err);
Here we need to send our error, so if there is an error then send the same as you did in line 7

2022-10-16 21:17 UTC, Raghad-Mezied commented on server/middlewares/Error.ts
> +});
The received error will have status and message, not the custom error.

2022-10-17 10:02 UTC, Raghad-Mezied submitted a review, later dismissed

2022-10-17 11:23 UTC, AhmedAbuSharar submitted a review, later dismissed

2022-10-17 11:23 UTC, Nader-SH submitted a review, later dismissed

2022-10-18 17:41 UTC, closed without merging