17 auth middleware for admin
CA-G12/MoH pull request #35
Opened 2022-10-16 19:52 UTC by AhmedAbuSharar

2022-10-16 20:06 UTC, Raghad-Mezied requested changes

2022-10-16 20:06 UTC, Raghad-Mezied commented on server/middlewares/adminAuth.ts
> +const pharmacyAuth = async (req: UserRequest['user'], res: Response, next: NextFunction) => {
Is it a middleware to check the admin or the pharmacy? match the func name and the role

2022-10-16 20:06 UTC, Raghad-Mezied commented on server/middlewares/adminAuth.ts
> +    throw new CustomError(401, 'You are not authenticated');
Pass the error to the next error middleware

2022-10-17 06:50 UTC, Ibtisam-Hemmo approved these changes, later dismissed

2022-10-17 09:05 UTC, Raghad-Mezied approved these changes

2022-10-17 09:06 UTC, Ibtisam-Hemmo approved these changes

2022-10-17 09:53 UTC, Nader-SH approved these changes

2022-10-17 09:53 UTC, merged