[GET] admin statistics
CA-G12/MoH pull request #44
Opened 2022-10-17 12:25 UTC by Ibtisam-Hemmo

2022-10-21 15:57 UTC, Raghad-Mezied requested changes

2022-10-21 15:57 UTC, Raghad-Mezied commented on server/routes/admin/overview.ts
> +adminRouter.get('/admin/statistics', getAdminOverview);
Just the admin can view the statistics, so pass the admin middleware.

2022-10-21 15:57 UTC, Raghad-Mezied commented on server/controllers/admin/overview.ts
> +  const allKindProductsCount= await expiredAndInStockProductsCount();
Since they are not independent of each other, so why await for one to do the other, use Promise.all to process them at the same time

2022-10-21 15:57 UTC, Raghad-Mezied commented on server/app.ts
>  app.use(authRouter);
Move to the router index

2022-10-21 19:18 UTC, Raghad-Mezied approved these changes

2022-10-22 06:18 UTC, Nader-SH approved these changes

2022-10-22 17:29 UTC, AhmedAbuSharar approved these changes

2022-10-22 17:37 UTC, merged