39 admin requests request
CA-G12/MoH pull request #45
Opened 2022-10-17 13:15 UTC by AhmedAbuSharar

2022-10-17 13:43 UTC, Raghad-Mezied requested changes

2022-10-17 13:43 UTC, Raghad-Mezied commented on server/test/index.test.ts
>  });
delete this test

2022-10-17 13:43 UTC, Raghad-Mezied commented on server/app.ts
> +// app.get('/data', (req: Request, res:Response) => res.send('Hello There!'));
Delete the commented line

2022-10-17 13:43 UTC, Raghad-Mezied commented on server/controllers/admin/requestStatus.ts
> +/* eslint-disable camelcase */
fix eslint

2022-10-17 13:43 UTC, Raghad-Mezied commented on server/controllers/admin/requestStatus.ts
> +  } catch (err : any) {
Use Joi validation to validate your status and requestId

2022-10-17 13:43 UTC, Raghad-Mezied commented on server/database/seeds/buildSeeds.ts
> +if (process.env.NODE_ENV === 'development') { buildSeeds(); }
Format

2022-10-17 13:45 UTC, Raghad-Mezied requested changes

2022-10-17 13:45 UTC, Raghad-Mezied commented on server/controllers/admin/requestStatus.ts
> +      res.json({ message: 'successful' });
edit the `message` to be `msg`, so you all have the same key

2022-10-18 09:10 UTC, Raghad-Mezied requested changes

2022-10-18 09:10 UTC, Raghad-Mezied commented on server/controllers/admin/requestStatus.ts
> +    }
If the data is not validated, then the validation function will throw the error and your catch will catch it. 
so if you are still in line 12 then your data is validated, which means no need to isValid and it doesn't return a boolean.

2022-10-18 09:46 UTC, Raghad-Mezied approved these changes

2022-10-18 09:47 UTC, Ibtisam-Hemmo approved these changes

2022-10-18 09:48 UTC, Nader-SH approved these changes

2022-10-18 09:48 UTC, merged