create apllication card
CA-G12/MoH pull request #53
Opened 2022-10-19 07:32 UTC by AhmedAbuSharar

2022-10-21 14:51 UTC, Raghad-Mezied requested changes

2022-10-21 14:51 UTC, Raghad-Mezied commented on client/src/App.tsx
> +};
Move the type

2022-10-21 14:51 UTC, Raghad-Mezied commented on client/src/components/admin/ApplicationCard.tsx
> +}
Update the imports and move the type

2022-10-21 14:51 UTC, Raghad-Mezied commented on client/src/components/admin/ApplicationCard.tsx
> +    <Box
Why this card is here? isn't it in another pull request?

2022-10-23 09:08 UTC, AhmedAbuSharar commented
![image](https://user-images.githubusercontent.com/91332305/197383909-fcda6d9f-d995-483e-b36b-7b219df568ed.png)

2022-10-23 10:07 UTC, Ibtisam-Hemmo approved these changes

2022-10-23 10:23 UTC, merged