Adding dashboard layout
CA-G12/MoH pull request #56
Opened 2022-10-19 18:34 UTC by Ibtisam-Hemmo

2022-10-20 11:06 UTC, Raghad-Mezied requested changes

2022-10-20 11:06 UTC, Raghad-Mezied commented on client/src/App.tsx
> +    // </>
remove commented line

2022-10-20 11:06 UTC, Raghad-Mezied commented on client/src/App.tsx
> +      path: "/",
add the admin in the main endpoint, and delete it from the the nested

2022-10-20 11:06 UTC, Raghad-Mezied commented on client/src/components/NavBar.tsx
> +import NotificationsIcon from "@mui/icons-material/Notifications";
you can import them { IconButton, MenuIcon, Toolbar} from "@mui/material"

2022-10-20 11:06 UTC, Raghad-Mezied commented on client/src/components/drawer.tsx
> +      </Link>
Why to duplicate this part, create an array and loop over it

2022-10-20 11:06 UTC, Raghad-Mezied commented on client/src/components/NavBar.tsx
> +        <AccountCircleIcon fontSize="large" />
Change this to a drop menu, add an option for logout, and make it works

2022-10-20 11:06 UTC, Raghad-Mezied commented on client/src/components/drawer.tsx
> +import logo from "../assets/logo.png";
import as above

2022-10-20 20:36 UTC, Raghad-Mezied submitted a review, later dismissed

2022-10-23 08:05 UTC, Raghad-Mezied approved these changes

2022-10-23 08:15 UTC, Nader-SH approved these changes

2022-10-23 08:40 UTC, AhmedAbuSharar approved these changes

2022-10-23 08:40 UTC, merged