54 admin applications section
CA-G12/MoH pull request #58
Opened 2022-10-20 08:29 UTC by AhmedAbuSharar

2022-10-21 14:39 UTC, Raghad-Mezied requested changes

2022-10-21 14:39 UTC, Raghad-Mezied commented on client/.eslintrc.json
> +        "camelcase": "off",
remove this role

2022-10-21 14:39 UTC, Raghad-Mezied commented on client/src/components/admin/ApplicationCard.tsx
> +
Move the types

2022-10-21 14:39 UTC, Raghad-Mezied commented on client/src/components/admin/ApplicationCard.tsx
> +import { Box, Typography } from '@mui/material';
Import them once, as you did in line 4

2022-10-21 14:39 UTC, Raghad-Mezied commented on client/src/components/admin/ApplicationSection.tsx
> +};
Update the import and move the type

2022-10-21 14:39 UTC, Raghad-Mezied commented on client/src/components/admin/ApplicationSection.tsx
> +    );
Why post? you are getting the data

2022-10-21 14:39 UTC, Raghad-Mezied commented on client/src/components/admin/ApplicationSection.tsx
> +    setCards(allApplications.data.rows);
Destructure the data

2022-10-21 14:39 UTC, Raghad-Mezied commented on client/src/components/admin/ApplicationSection.tsx
> +  };
You are updating the status here so its put not post, right?

2022-10-21 14:39 UTC, Raghad-Mezied commented on client/src/components/admin/ApplicationSection.tsx
> +  );
Add pagination and loading

2022-10-21 14:40 UTC, Raghad-Mezied commented
Don't forget to add a screenshot from your work in the description of the pull request.

2022-10-23 21:49 UTC, AhmedAbuSharar commented
![image](https://user-images.githubusercontent.com/91332305/197419834-ba76491f-8e59-4370-ba39-821adb3c37e3.png)

2022-10-25 06:56 UTC, Nader-SH submitted a review, later dismissed

2022-10-25 07:55 UTC, Ibtisam-Hemmo submitted a review, later dismissed

2022-10-25 08:05 UTC, merged